networks:
  trans-networks:
    name: trans-networks
    driver: bridge

volumes:
  postgres:
    driver: local
    name: postgres
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  django:
    driver: local
    name: django
    driver_opts:
      type: none
      o: bind
      device: ./django
  static:
  media:

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-bookworm
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - trans-networks
    restart: unless-stopped
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - django:/home/django/ft_transcendence
      - static:/home/django/ft_transcendence/static
      - media:/home/django/ft_transcendence/media
    networks:
      - trans-networks
    depends_on:
      - postgres
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - static:/home/django/ft_transcendence/static
      - media:/home/django/ft_transcendence/media
    networks:
      - trans-networks
    depends_on:
      - django
    restart: unless-stopped