FROM nginx:stable

RUN apt update
RUN apt -y install openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/key.pem \
    -out /etc/ssl/certs/cert.pem \
    -subj "/C=TH/ST=Bangkok/L=Bangkok/O=42Bangkok/OU=Narwhals/CN=tkraikua"

COPY ./nginx.conf /etc/nginx/nginx.conf