# Generated by Django 5.0.6 on 2024-06-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_room_user1_room_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
