# Generated by Django 5.0.4 on 2024-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_active_customuser_draws_customuser_loses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner_image',
            field=models.ImageField(default='Background.png', upload_to='banner_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile-pic.png', upload_to='profile_pics'),
        ),
    ]
