# Generated by Django 5.0.4 on 2024-04-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
