# Generated by Django 5.0.6 on 2024-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner_image',
            field=models.ImageField(default='banner_pics/default_banner_image.png', upload_to='banner_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default_profile_image.png', upload_to='profile_pics'),
        ),
    ]
