# Generated by Django 5.1.3 on 2024-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
