# Generated by Django 5.1.3 on 2024-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_agree_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
