# Generated by Django 5.1.3 on 2024-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_is_agree_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
