# Generated by Django 5.0.6 on 2024-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField()),
                ('player1', models.CharField()),
                ('player2', models.CharField(default='to-be-decide')),
                ('player_in_room', models.IntegerField(default=0)),
                ('ball_x', models.FloatField(default=400)),
                ('ball_y', models.FloatField(default=200)),
                ('paddle1_y', models.FloatField(default=150)),
                ('paddle2_y', models.FloatField(default=150)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
            ],
        ),
    ]
