# Generated by Django 5.0.8 on 2024-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='game_type',
            field=models.TextField(default='', max_length=20, verbose_name='Game Type'),
        ),
    ]
