# Generated by Django 5.0.6 on 2024-06-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='game_state',
            field=models.TextField(default=None, null=True),
        ),
    ]
