# Generated by Django 5.1.3 on 2025-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_tournament_player_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last_round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
