# Generated by Django 5.0.6 on 2024-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_ponggame_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='plyaer_in_room',
            field=models.IntegerField(default=0),
        ),
    ]
