# Generated by Django 5.0.6 on 2024-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_matchtournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtournament',
            options={'ordering': ['match_date']},
        ),
        migrations.AddField(
            model_name='matchtournament',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
