# Generated by Django 5.0.6 on 2024-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_matchtournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
    ]
