# Generated by Django 5.0.6 on 2024-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_tournament_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='schedule',
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='opponents',
            field=models.ManyToManyField(blank=True, to='game.tournamentparticipant'),
        ),
    ]
