# Generated by Django 5.0.6 on 2024-06-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_tournament_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='opponents',
        ),
    ]
