# Generated by Django 5.0.6 on 2024-06-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_tournamentparticipant_opponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtournament',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchtournament',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
