# Generated by Django 5.0.6 on 2024-06-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_matchtournament_player1_ready_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_x', models.FloatField(default=400)),
                ('ball_y', models.FloatField(default=200)),
                ('ballSpeedX', models.IntegerField(default=5)),
                ('ballSpeedY', models.IntegerField(default=5)),
                ('ballSize', models.IntegerField(default=5)),
                ('paddle1_y', models.FloatField(default=150)),
                ('paddle2_y', models.FloatField(default=150)),
                ('paddleWidth', models.IntegerField(default=10)),
                ('paddleHeight', models.IntegerField(default=100)),
                ('paddleSpeed', models.IntegerField(default=10)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.matchtournament')),
            ],
        ),
    ]
