# Generated by Django 5.0.6 on 2024-06-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_tournamentponggame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentponggame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.matchtournament', unique=True),
        ),
    ]
